### ISSUE TITLE
How to add a second language

### ISSUE THREAD

**Issue by ghost** [soimort/translate-shell#342] opened 2020-04-11 19:12 UTC
Thanks for your ordinary work! I would like to ask you a question. How to add a second language so that when source sentences is my locale laguage, it could translate into the second language automatically? Using two target language is not what I want. Or could I determine what language the source sentences is before I use translation-shell?

**Comment by soimort** [comment] 2020-04-11 20:25
Duplicate of #298 and #153.

**Closed as completed by soimort** 2020-04-11 20:25 UTC
Labels: duplicate
