### ISSUE TITLE
anyway to save the history

### ISSUE THREAD

**Issue by cryoguy** [soimort/translate-shell#251] opened 2018-08-14 19:56 UTC
A great tool!  does anyone know a way to save the history (word list)?

**Comment by soimort** [comment] 2018-08-14 20:07
Your shell should be capable of saving some kind of command history (in `~/.bash_history` or `~/.zsh_history`) which you can grep into.

Regarding `trans` itself, this is a duplicate of #230.

**Closed as completed by soimort** 2018-08-14 20:07 UTC
Labels: duplicate
