### ISSUE TITLE
Use default google translate get wrong language result.

### ISSUE THREAD

**Issue by zw963** [soimort/translate-shell#312] opened 2019-07-17 17:10 UTC
It work pretty well for quite a long time, but it broken in recent days.

When i run like this:  `usr/local/bin/trans zh-CN:en '出错'`,  get garbled code as follow image.

![image](https://user-images.githubusercontent.com/549126/61395486-1d649e80-a8f8-11e9-9ccf-ae2e2ade59e9.png)

but, when from 'en => zh-CN', it still work well.

Thank you.

**Comment by overrider** [comment] 2019-07-23 06:19
I get the same issue. Whats funny is that if you repeatedly paste the chinese source text into the shell, eventually it will display right. It seems as if the server response is garbled already somehow.

**Comment by soimort** [comment] 2019-07-25 12:37
Duplicate of #310.

**Closed as completed by soimort** 2019-07-25 12:37 UTC
Labels: duplicate

**Comment by fuloating** [comment] 2019-08-22 07:50
I am now getting only garbled results, retried several times but all garbled unlike one of the comments above. I tried translating from japanese to english
