### ISSUE TITLE
Translate Shell returns empty string

### ISSUE THREAD

**Issue by rinatkhanov** [soimort/translate-shell#47] opened 2015-04-08 08:21 UTC
![gif](http://g.recordit.co/5GpUgBfnxd.gif)

Translate Shell used to work perfectly, but it suddenly stopped showing translations for whatever reason. Check out attached GIF. Any ideas?

OS X 10.10.2, iTerm 2 with zsh.

**Comment by soimort** [comment] 2015-04-08 08:31
Thanks for the report. This is a duplicate of #45 and has been fixed by #46. A new release is underway.

**Closed as completed by soimort** 2015-04-08 08:31 UTC
