### ISSUE TITLE
translate from ru

### ISSUE THREAD

**Issue by aronsx** [soimort/translate-shell#351] opened 2020-05-31 15:26 UTC
trans ru:en "карман"
ÐºÐ°ÑÐ¼Ð°Ð½

Ð € Ð € Ð½

ÐºÐ°ÑÐ¼Ð°Ð½: варианты перевода
[ Русский -> English ]

ÐºÐ°ÑÐ¼Ð°Ð½
    Ð € Ð € Ð½, ÐºÐ ° Ñ Ð¼Ð ° Ð½

---
how to show the correct encoding?

**Comment by adawdp** [comment] 2020-06-23 19:41
Hello! 
Maybe the problem is in your system?

trans ru:en "карман"
Pocket ❰???❱

**Comment by soimort** [comment] 2020-06-23 21:41
Old bug #310 that has been fixed by d3f9251529b14991ae1a69f9be4182a47ab8e30b. Please upgrade your translate-shell to a newer version (0.9.6.12).

If the issue persists, please post the output of `trans -V` here.

**Closed as completed by soimort** 2020-06-23 21:41 UTC
Labels: duplicate, invalid
