### ISSUE TITLE
Why is translate-shell so slow?

### ISSUE THREAD

**Issue by qwer1304** [soimort/translate-shell#236] opened 2018-06-30 08:46 UTC
With all engines the response is very slow, e.g. (from time):
Yandex
real    0m7.924s
user    0m0.406s
sys     0m3.656s 

Google
real    0m5.959s
user    0m2.156s
sys     0m3.266s

In a browser, the response is instantenous

**Comment by soimort** [comment] 2018-06-30 10:38
trans was written in Awk, whose implementation is known to be inefficient due to its historical legacy, especially so for heavy operations on arrays (#59). But after all, initializing the gawk interpreter process also adds a lot to the overhead, and it's unavoidable -- Translating in an (already open) web browser is always faster than any CLI tool because there is no more external process to invoke.

Your `sys` time is significantly more consuming (~3s), that probably indicates that you're on a slow network (since this is the part where network IO counts). Assume that the network is in an ideal status, it should be relatively trivial compared to `user` time:

```
real	0m1.491s
user	0m1.390s
sys	0m0.060s
```

**Comment by qwer1304** [comment] 2018-06-30 12:20
I timed ping of translate.google.com on my machine:
time ping -c 1 translate.google.com

rtt min/avg/max/mdev = 71.445/71.445/71.445/0.000 ms

real    0m0.101s
user    0m0.000s
sys     0m0.016s

So it doesn't look like the slowness of the connection is the issue.

time ./trans -b -t ru -e google hello
real    0m3.634s
user    0m0.750s
sys     0m2.531s

PS This happens on a Windows 10 x64 1803 machine in BOTH WSL and Cygwin64 environments

**Comment by soimort** [comment] 2018-06-30 12:44
ICMP echoes are different from regular TCP requests which carry actual data, small ping latency doesn't necessarily mean a good connection. But if network IO isn't the problem, then it's pretty weird that `sys` time takes so long (even much longer than `user` in your case).

You could try to `curl` the Google API directly and see how fast you got:

```
$ time curl -A 'Mozilla' "http://translate.googleapis.com/translate_a/single?client=gtx&dt=bd&dt=ex&dt=ld&dt=md&dt=rw&dt=rm&dt=ss&dt=t&dt=at&dt=qc&sl=auto&tl=en&q=test" &>/dev/null
```

**Comment by qwer1304** [comment] 2018-06-30 13:06
curl results:
real    0m0.346s
user    0m0.016s
sys     0m0.000s

**Comment by soimort** [comment] 2018-06-30 13:20
This looks pretty weird to me. Can you please try to time the following:

```
$ time trans -h
$ time trans -e deepl :fr test
```

**Comment by qwer1304** [comment] 2018-06-30 13:24
time trans -h
real    0m2.181s
user    0m0.094s
sys     0m2.047s

===============

time trans -e deepl :fr test
real    0m3.664s
user    0m0.156s
sys     0m2.125s

=================

time trans -e google :fr test
real    0m3.278s
user    0m1.125s
sys     0m1.922s

**Comment by soimort** [comment] 2018-06-30 13:42
OK. `trans -h` does not do anything effectively, nor does it access the Internet. If it takes 2s to finish, it's definitely something wrong about this specific platform (Windows), its gawk port, or both.

I have no idea how you installed `trans` at all. Please grab a clean version from git and run it directly. If the long `sys` time is still reproducible, then I'm out of ideas.

```
$ time ./translate -no-init -V
```

**Comment by qwer1304** [comment] 2018-06-30 14:20
Hmm, getting somewhere:

I got everything from git, did a make

Now time ./translate -no-init -V gives:
real    0m0.467s
user    0m0.047s
sys     0m0.391s

but time build/trans -no-init -V gives
real    0m2.662s
user    0m0.188s
sys     0m2.469s

So it's the result of make build which is problematic

PS Before, I just downloaded trans executable from git.io/trans

**Comment by qwer1304** [comment] 2018-07-01 07:03
Another weird thing I noticed with translate (not trans):
google engine is much faster than other (e.g., yandex), but direct api invocation to yandex is fast!
Here're the timings:

google:
time ./translate -b -t ru -e google tardiness
медлительность

real    0m0.861s
user    0m0.125s
sys     0m0.469s

time curl -A 'Mozilla' "http://translate.googleapis.com/translate_a/single?client=gtx&dt=bd&dt=ex&dt=ld&dt=md&dt=rw&dt=rm&dt=s
s&dt=t&dt=at&dt=qc&sl=auto&tl=en&q=tardiness" &>/dev/null

real    0m0.358s
user    0m0.000s
sys     0m0.063s

Yandex:

time ./translate -b -t ru -e yandex tardiness
опоздание

real    0m4.620s
user    0m0.156s
sys     0m0.672s

time curl -A 'Mozilla' "https://translate.yandex.net/api/v1.5/tr.json/translate?key=`<KEY`>&text=tardiness&lang=en-ru"
{"code":200,"lang":"en-ru","text":["опоздания"]}
real    0m1.063s
user    0m0.016s
sys     0m0.047s

Is yandex response decoding sub-optimal?

Here's the timing with -dump option:
time ./translate -b -t ru -e yandex -dump tardiness
{"code":200,"lang":"en-ru","text":["опоздание"]}

real    0m2.423s
user    0m0.063s
sys     0m0.547s

It's still higher than direct API call though

**Comment by soimort** [comment] 2018-07-01 15:39
To clarify, the Yandex supporting engine works differently than others:

1. It makes multiple requests to the API server (for stuff like scraping the key from the page, getting the translation, getting the dictionary entry if any, getting the transliteration of words, etc.), so it's not surprising that it takes much longer than just one request, given that you already have a personal API key in hand. Unlike Yandex, Google Translate encloses everything in one single big response, which makes things organized and faster.

2. [`YandexTranslate.awk`](https://github.com/soimort/translate-shell/blob/develop/include/Translators/YandexTranslate.awk) uses `curl` to access the API, because Yandex's server does not allow plain HTTP and gawk does not support TLS / HTTPS natively. Of course, calling external processes always has some expense.

**Comment by qwer1304** [comment] 2018-07-01 17:00
Thx, let's try and resolve the translate vs trans issue:

```
Hmm, getting somewhere:

I got everything from git, did a make

Now time ./translate -no-init -V gives:
real 0m0.467s
user 0m0.047s
sys 0m0.391s

but time build/trans -no-init -V gives
real 0m2.662s
user 0m0.188s
sys 0m2.469s

So it's the result of make build which is problematic
```

**Comment by soimort** [comment] 2018-07-01 17:27
I can't figure out why, but it could be something specific to bash's Windows port that makes `trans` particularly slow. (`build/trans` is a shell script that wraps everything altogether like a heredoc. It does have some performance degradation compared to direct awk invocation, but it shouldn't be *this* much)

Unfortunately I'm not able to dig into this further since I'm not on Windows. If you're not using bash, switch to bash (which can also save some time). On my Linux machine both are reasonably fast: 

```
 $ time ./translate -h &>/dev/null

real	0m0.001s
user	0m0.001s
sys	0m0.000s

$ time ./translate 'hello world' &>/dev/null

real	0m0.446s
user	0m0.358s
sys	0m0.047s

$ time build/trans -h &>/dev/null

real	0m0.002s
user	0m0.002s
sys	0m0.000s

$ time build/trans 'hello world' &>/dev/null

real	0m0.564s
user	0m0.417s
sys	0m0.112s
```

**Comment by qwer1304** [comment] 2018-07-01 19:03
I'm using bash

Trying to build trans on Cygwin64 and getting:
gawk: build.awk:209: fatal: attempt to use scalar `Includes' as an array

Could you take a look

**Comment by soimort** [comment] 2018-07-01 19:54
I don't have a cygwin64 environment for testing, probably can't help then.

Make sure you have installed the latest version of gawk, and that you're running `make` under the same directory, and that directory is a clean copy of translate-shell. You might also want to run `gawk -f test.awk` for some sanity check.

**Comment by qwer1304** [comment] 2018-07-02 05:28
The problem seems to be with the file *.awk in include/Translators.
Cygwin has trouble with it, so git fails, zip translates it to _.awk, and then build fails to include in translate the translators.
Is it possible to change the name to something more Windows friendly?

PS I forced _.awk into *.awk after unzipping (git fails) and now make works

**Comment by soimort** [comment] 2018-07-02 12:13
Then your zip program is the one to blame because it doesn't preserve original filenames ( :

You can try out the [asterisk-free](https://github.com/soimort/translate-shell/tree/asterisk-free) branch which gets rid of this special name.

**Comment by qwer1304** [comment] 2018-07-02 12:32
Nope, still getting gawk: build.awk:209: fatal: attempt to use scalar `Includes' as an array and translate become corrupted

From looking at build.awk, wouldn't you also need to change line 139?
Doesn't it look for a * in the name?

**Comment by soimort** [comment] 2018-07-02 12:39
Use git to clone that branch.

**Comment by qwer1304** [comment] 2018-07-02 12:45
Issue solved
Turns out I was using a Windows git, so it added CRLF to the filles which screwed up match
Now with Unix git all's fine
The asterisk-free branch is not needed, Unix git manages to deal with *.awk file

Sorry for the hassle

**Comment by soimort** [comment] 2018-07-06 20:03
I'm closing this issue since it is vague what this slowness is about and what is the cause of it. If there are specific technical suggestions for a certain platform (WSL or Cygwin, for instance), you are welcome to open another issue for discussion.

**Closed as completed by soimort** 2018-07-06 20:03 UTC
Labels: question
