### ISSUE TITLE
Empty output for any input

### ISSUE THREAD

**Issue by aghasemi** [soimort/translate-shell#48] opened 2015-04-08 08:21 UTC
Hi,
Thanks for the good work. I was desperately looking for something like this. However, when I installed it via apt-get on Ubuntu 15.04, I got an empty output for any input I typed (It seems to be a blank line). No message or error or,...
Do you have any idea what should I do? I tested installing using the wget method but again the same result. 
Thanks
Best

**Comment by soimort** [comment] 2015-04-08 08:31
Thanks for the report. This is a duplicate of #45 and has been fixed by #46. A new release is underway.

**Closed as completed by soimort** 2015-04-08 08:31 UTC
