### ISSUE TITLE
Translation with DeepL no longer works

### ISSUE THREAD

**Issue by rememberYou** [soimort/translate-shell#239] opened 2018-07-08 07:47 UTC
First of all, a big thank you for this useful package.

I allow myself to open this issue because I haven't been able to get the translation with [DeepL](https://www.deepl.com/translator) for a few days now.

For example, you can reproduce this bug with: `trans --brief :en -e deepl "Bonjour"`

**NOTE:** if I don't use DeepL as a translation engine, it works perfectly.

I can provide some additional information if necessary.

**Comment by soimort** [comment] 2018-07-08 10:08
Duplicate of #237, which is already fixed by 2399bb7.

**Closed as completed by soimort** 2018-07-08 10:08 UTC
Labels: duplicate
