### ISSUE TITLE
Feature request: list of stuff not to translate

### ISSUE THREAD

**Issue by JohnnyKing94** [soimort/translate-shell#191] opened 2017-09-12 14:08 UTC
Is it possible to include an option where we include a list of words/special_codes/strings not to translate? That would be cool

**Comment by rsvp** [comment] 2017-09-12 17:11
Good idea... does upstream, for example, Google Translate, have 
***special strings*** which always translate to themselves? 
Then downstream, we could use  have an **exclusion list** 
used to `s/exclude1/SPECIAL1/` with respect to the input, 
then reverse the substitutions from the upstream output.

**Comment by JohnnyKing94** [comment] 2017-09-12 18:25
I'd like also to use regex in this list... consider i have special codes like `Press <<1>> button` or `The player name is <<player_name>>` or new lines escaped, like `blablabla\nblabla`... and all the engines i've tested they exapnd the special charcters or try to mess by translating the variable names (like player_name)... 

+1 for also including the regex expr

**Comment by soimort** [comment] 2017-09-12 19:18
Duplicate of #75.

**Closed as completed by soimort** 2017-09-12 19:18 UTC
Labels: duplicate
