### ISSUE TITLE
Strange behavior with authenticated proxy

### ISSUE THREAD

**Issue by Ziltosh** [soimort/translate-shell#339] opened 2020-02-21 11:35 UTC
Hello,

I currently have 2 environments where I use this tool (github clone version).
#1 A Macbook Pro
```
Translate Shell       0.9.6.11-git:598b6c7

platform              Darwin
terminal type         xterm
bi-di emulator        [N/A]
gawk (GNU Awk)        5.0.1
fribidi (GNU FriBidi) 1.0.8
audio player          [NOT INSTALLED]
terminal pager        less
web browser           open
user locale           fr_FR.UTF-8 (French)
home language         fr
source language       auto
target language       fr
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
ip version            [DEFAULT]
theme                 default
init file             [NONE]
```
#2 A docker ubuntu image
```
Translate Shell       0.9.6.11-git:598b6c7

platform              Linux
terminal type         xterm
bi-di emulator        [N/A]
gawk (GNU Awk)        4.1.4
fribidi (GNU FriBidi) [NOT INSTALLED]
audio player          mplayer
terminal pager        less
web browser           xdg-open
user locale           en_US.UTF-8 (English)
home language         en
source language       auto
target language       en
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
ip version            [DEFAULT]
theme                 default
init file             [NONE]
```

I use a proxy that requires authentication and I encounter a rather strange problem, here are some requests and their results:
#1
```
./translate -x "http://user:password@proxy:port" :de "Where is Bryan ?" -e google -D
  16 bytes > HTTP/1.1 200 OK
...
Wo ist Bryan?
```
Everything OK.

#2
```
./translate -x "http://user:password@proxy:port" :de "Where is Bryan ?" -e google -D
...
  48 bytes > HTTP/1.1 407 Auth Failed (code: wrong_password)
content = '''
...
'''
tokens =
ast =
[ERROR] Oops! Something went wrong and I can't translate it for you :(
```
Same user:password > 407 Auth Failed

After some research, I modify the code to force the use of curl:
#1
```
./translate -x "http://user:password@proxy:port" :de "Where is Bryan ?" -e google -D
# In Translate.awk > getResponse()
>> disable http, goto curl
# In Utils.awk > curl()
>> force curl()
Wo ist Bryan?
```
Works fine.

#2
```
./translate -x "http://user:password@proxy:port" :de "Where is Bryan ?" -e google -D
# In Translate.awk > getResponse()
>> disable http, goto curl
# In Utils.awk > curl()
>> force curl()
Wo ist Bryan?
```
Works fine too.

Do you have any ideas? 
Otherwise adding an option to force the use of curl instead of the http library, maybe ?

I try with export HTTP_PROXY and no -x option, same problem with http, no problem with curl.

Thank you.

EDIT: The password contains no special characters, only numbers and letters.

**Comment by soimort** [comment] 2020-02-21 15:12
The syntax of the `-x` option is as follows

```
    -x HOST:PORT, -proxy HOST:PORT
        Use HTTP proxy on given port.
```

So please try again without the `http://` part.

**Comment by soimort** [comment] 2020-02-21 15:20
By the way, translate-shell only supports basic proxy authentication for this `user:password@HOST:PORT` syntax. So if your HTTP proxy uses digest authentication, that's probably not going to work.

**Comment by Ziltosh** [comment] 2020-02-21 15:27
Hi,

Thank you.

I tried without http:// but same result. Work well on OSX (both http or curl), work only with curl on my docker image.

It's a basic auth http proxy I think.

**Comment by soimort** [comment] 2020-02-21 15:54
That would be indeed strange. If you can compare the request headers sent by #1, #2 and `curl`, you might be able to spot something different (pay attention to the line containing `Proxy-Authorization: Basic`).

**Comment by Ziltosh** [comment] 2020-02-21 21:40
I found.

I added some debug lines in Translate.awk to display the headers.

On my Macbook Pro:
```
...
User-Agent: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
Proxy-Authorization: Basic xxx

close HttpService
end getResponse
Where is Bryan ?

Wo ist Bryan?
```

On Linux Docker Image:
```
Proxy-Authorization: Basic yyy

close HttpService
end getResponse
[ERROR] Oops! Something went wrong and I can't translate it for you :(
```

Same command line but not the same Proxy-Authorization...
If I base64 decode xxx and yyy, the second one on my Linux image is my user:password but cut at 57 characters, that's not the case on my Mac. I don't know why.
user:password is 60 characters long.

With the curl function, there is not this problem, the proxy is correctly put in the command with the argument --proxy and full user:password.

**Comment by soimort** [comment] 2020-02-22 22:28
Thanks for the information. 

The cause of this bug is now clear. macOS / BSD's `base64` does not wrap lines by default, while GNU's `base64` wraps lines into a fixed length, hence long user:password gets truncated incorrectly. Should be fixed in the `develop` branch.

**Closed as completed by soimort** 2020-02-22 22:27 UTC
Labels: bug
