### ISSUE TITLE
trans converting world to auto correct, even i use -no-autocorrect

### ISSUE THREAD

**Issue by helpinghandindia1** [soimort/translate-shell#460] opened 2022-09-24 07:26 UTC
@soimort 

Hi
pls guide for a small issue.
I need hindi to english conversion same as i typed/need.
I tried with many option like -no-autocorrect and others but always it is using auto correct and change meaning of source word.
example 
trans -no-autocorrect -b सोनूसिंह
trans -no-autocorrect -b कवितासंतरा
I need conversion in English as same source/word but trans converting/translating them to their english meaning.
waiting for reply.

**Comment by soimort** [comment] 2022-09-30 12:51
> I need conversion in English as same source/word
> but trans converting/translating them to their english meaning.

I do not understand what exactly you are trying to achieve here, however I assume you meant [romanization of Devanagari](https://en.wikipedia.org/wiki/Devanagari_transliteration). In that case, it's a duplicate of #459.

**Closed as completed by soimort** 2022-09-30 12:51 UTC
Labels: duplicate
