### ISSUE TITLE
forvo engine to support Hebrew pronunciation

### ISSUE THREAD

**Issue by OrionRandD** [soimort/translate-shell#407] opened 2021-06-29 13:44 UTC
Please add suport for forvo.
Making an engine???!!!
So that Hebrew pronunciation can be possible.
Since Google translator has no support for Hebrew speaker for a long time now.
It is unbealivable that Google does not support sounds for Hebrew language at this 
point of its technology and resources

https://forvo.com/word/%D7%A9%D7%9C%D7%95%D7%9D/

**Comment by soimort** [comment] 2021-06-29 14:08
Thanks for the suggestion. (Closing as it is a duplicate of #253.)

**Closed as completed by soimort** 2021-06-29 14:08 UTC
Labels: duplicate

**Comment by OrionRandD** [comment] 2021-06-30 20:36
Yeah! But the suggestion was make in 2018...
Please add this. People who study Hebrew and Arabic - right-to-left -
languages would
appreciate it.

**Comment by soimort** [comment] 2021-06-30 21:08
For now the priority is probably to fix the support for the Bing engine, which supports Hebrew pronunciation as well.

**Comment by OrionRandD** [comment] 2021-06-30 21:15
Great!
But do not forget forvo.
Because it is real native people speaking and the quality is just amazing.
You can try it online and see for yourself....
