### ISSUE TITLE
empty output

### ISSUE THREAD

**Issue by andreineculau** [soimort/translate-shell#50] opened 2015-04-14 06:14 UTC
no idea if it's related to #44 (haven't checked the code)
but translations comes out empty now (after upgrading 22.5 to 23)

```
$ trans -t zh+ja word

────────────────────────────────────────────────────────────────

```

**Comment by soimort** [comment] 2015-04-14 06:54
[Please](https://github.com/soimort/translate-shell/blob/develop/CONTRIBUTING.md) provide the output of `trans -version`, and your network setting if possible, otherwise it's very hard for me to look into problems like this since I have no helpful information about your issue. 

(I can't reproduce it myself, but Google may ban some IPs from time to time. It's most likely the reason, but again, it's just a guess with no factual basis...)

**Comment by andreineculau** [comment] 2015-04-14 07:09
Had to move to another location, and I'm now getting the behavior in #44

```
$ trans -version
Translate Shell 0.8.23

gawk (GNU Awk)        4.1.1
fribidi (GNU FriBidi) [NOT INSTALLED]
User Language         English (English)
```

```
$ ip
173.38.220.62
```

Will come back when I change locations again.

On Tue, Apr 14, 2015 at 8:54 AM, Mort Yao notifications@github.com wrote:

> Please
> https://github.com/soimort/translate-shell/blob/develop/CONTRIBUTING.md
> provide the output of trans -version, and your network setting if
> possible, otherwise it's very hard for me to look into problems like this
> since I have no helpful information about your issue.
> 
> (I can't reproduce it myself, but Google may ban some IPs from time to
> time. It's most likely the reason, but again, it's just a guess with no
> factual basis...)
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/soimort/translate-shell/issues/50#issuecomment-92656810
> .

## 

andreineculau.com http://www.andreineculau.com

**Comment by dorian-marchal** [comment] 2015-04-15 12:49
Same error, here (empty output).
I think that an Ubuntu update broke something. It used to work fine.

I got the same issue on my both laptops (Ubuntu 14.04 and Ubuntu 12.04).
At work and at home, (different IP addresses). It happened at the same time on both machines.

```
Translate Shell 0.8.22.5

gawk (GNU Awk)        4.1.1
fribidi (GNU FriBidi) [NOT INSTALLED]
User Language         French (Français)
```

EDIT: I tried with a proxy, I got the same error.

**Comment by soimort** [comment] 2015-04-15 12:54
@dorian-marcha You should update to 0.8.23.

**Comment by soimort** [comment] 2015-04-15 12:55
@dorian-marchal You should update to 0.8.23.

**Comment by dorian-marchal** [comment] 2015-04-15 12:58
It fixed the issue, sorry :+1:

**Comment by soimort** [comment] 2015-05-25 01:52
The issue seems to be on the network, not translate-shell itself. Closing.

**Closed as completed by soimort** 2015-05-25 01:52 UTC
Labels: CNR
