### ISSUE TITLE
Japanese input adds "null" to input

### ISSUE THREAD

**Issue by mpapushin** [soimort/translate-shell#171] opened 2017-04-05 05:56 UTC
Any Japanese input string is translated as if the word "null" were appended to the end of the string, producing garbled output

Example output:
$ trans -no-ansi -l en -s ja "日本語"
日本語 null
(null Nihongo)

Japanese null
/null null/

Definitions of 日本語 null
[ 日本語 -> English ]

noun
    Japanese
        日本語, 日本人, 邦人, 倭人, 日本側

$ trans -V
Translate Shell       0.9.4

platform              Linux
gawk (GNU Awk)        4.1.4
fribidi (GNU FriBidi) 0.19.7
audio player          mpv
terminal pager        less
terminal type         xterm
user locale           en_US.UTF-8 (English)
home language         en
source language       auto
target language       en
translation engine    google
proxy                 [NONE]
user-agent            Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/602.1 (KHTML, like Gecko) Version/8.0 Safari/602.1 Epiphany/3.18.2
theme                 default
init file             [NONE]

**Comment by soimort** [comment] 2017-04-05 08:15
Can't reproduce.

Please update to 0.9.6.1 first, and, if it ever happens again, report the output with `-debug`.

**Comment by soimort** [comment] 2017-04-05 19:28
Oh, this is reproducible now, for every translation in every language that comes from Google Translate's backend. It was a trivial change in their API servers (the `null` now emerges so as to form valid JSON responses). Should be fixed in `trans` soon.

**Closed as completed** 2017-04-05 19:53 UTC
