### ISSUE TITLE
character '=' is converted to Unicode code 'u003d' on command output

### ISSUE THREAD

**Issue by KVAnton-WEB** [soimort/translate-shell#429] opened 2021-10-18 16:02 UTC
Сommand:   
`trans 'work = wolf'`

Output: 
```
work u003d wolf

работа u003d волк
(rabota u003d volk)

work u003d wolf: варианты перевода
[ English -> Русский ]

work u003d wolf
    работа u003d волк, work u003d волк
```

**Comment by soimort** [comment] 2021-10-18 19:17
Duplicate of #420. (already fixed)

**Closed as completed by soimort** 2021-10-18 19:17 UTC
Labels: duplicate
