### ISSUE TITLE
Is there a way not to translate some words and something inside special tags?

### ISSUE THREAD

**Issue by mav1** [soimort/translate-shell#322] opened 2019-09-02 19:37 UTC
Hello. I want to translate something like this (for example, to german language or another one):

_This is some text. And some more text...and more and more... SOMESTRANGEWORD And a little bit of code:_

```
<mycode>
echo "hello world";
</mycode>
```
_And some more stupid text..._

So, is there a way not to translate SOMESTRANGEWORD and also everything between &lt;mycode&gt; and &lt;/mycode&gt; ? Where i can set these exceptions?

**Comment by soimort** [comment] 2019-09-02 20:10
Duplicate of #214 and #75.

**Closed as completed by soimort** 2019-09-02 20:10 UTC
Labels: duplicate
